import type { EChartsOption } from 'echarts'
import type { BurndownDay, CumulativeFlowDay, CyclePoint, ThroughputPoint } from '@/api/analytics'

const colours = ['#2563eb', '#7c3aed', '#0891b2', '#d97706', '#dc2626', '#16a34a']
const base = (): EChartsOption => ({ color: colours, textStyle: { fontFamily: 'Instrument Sans, sans-serif' }, tooltip: { trigger: 'axis' }, grid: { left: 42, right: 18, top: 24, bottom: 36 } })
export const burndownOption = (days: BurndownDay[]): EChartsOption => ({ ...base(), xAxis: { type: 'category', data: days.map(day => day.day.slice(5)) }, yAxis: { type: 'value', min: 0 }, series: [
  { name: 'Remaining', type: 'line', smooth: true, data: days.map(day => day.remaining), areaStyle: { opacity: .12 } },
  { name: 'Ideal', type: 'line', lineStyle: { type: 'dashed' }, symbol: 'none', data: days.map(day => day.idealRemaining) },
  { name: 'Scope', type: 'line', data: days.map(day => day.scope) },
] })
export const velocityOption = (sprints: { sprintName: string; committedPoints: number; completedPoints: number }[]): EChartsOption => ({ ...base(), legend: { bottom: 0 }, xAxis: { type: 'category', data: sprints.map(s => s.sprintName) }, yAxis: { type: 'value', min: 0 }, series: [{ name: 'Committed', type: 'bar', data: sprints.map(s => s.committedPoints) }, { name: 'Completed', type: 'bar', data: sprints.map(s => s.completedPoints) }] })
export const cfdOption = (days: CumulativeFlowDay[]): EChartsOption => ({ ...base(), legend: { bottom: 0 }, xAxis: { type: 'category', data: days.map(day => day.day.slice(5)) }, yAxis: { type: 'value' }, series: Object.keys(days.flatMap(day => Object.keys(day.counts)).reduce((all, key) => ({ ...all, [key]: true }), {})).map(key => ({ name: key, type: 'line', stack: 'items', areaStyle: {}, data: days.map(day => day.counts[key] ?? 0) })) })
export const cycleOption = (items: CyclePoint[]): EChartsOption => ({ ...base(), tooltip: { trigger: 'item', formatter: params => { const data = (Array.isArray(params) ? params[0] : params)?.data as [number, number, string]; return `${data?.[2] ?? ''}<br>Lead: ${data?.[0] ?? 0}d · Cycle: ${data?.[1] ?? 0}d` } }, xAxis: { name: 'Lead time (days)', type: 'value', min: 0 }, yAxis: { name: 'Cycle time (days)', type: 'value', min: 0 }, series: [{ type: 'scatter', symbolSize: 10, data: items.map(item => [item.leadDays, item.cycleDays, item.itemKey]) }] })
export const throughputOption = (points: ThroughputPoint[]): EChartsOption => ({ ...base(), legend: { bottom: 0 }, xAxis: { type: 'category', data: points.map(point => point.weekOf) }, yAxis: { type: 'value', minInterval: 1 }, series: [{ name: 'Human', type: 'bar', stack: 'work', data: points.map(point => point.humanCount) }, { name: 'Agent', type: 'bar', stack: 'work', data: points.map(point => point.agentCount) }] })
export function csvDownload(name: string, rows: (string | number | null | undefined)[][]) { const escape = (value: string | number | null | undefined) => `"${String(value ?? '').replaceAll('"', '""')}"`; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([rows.map(row => row.map(escape).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' })); link.download = name; link.click(); URL.revokeObjectURL(link.href) }
