// <auto-generated />
using System;
using Aictiq.Modules.Automation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aictiq.Modules.Automation.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    [Migration("20260917112653_PlaybooksAndProjectFactorySettings")]
    partial class PlaybooksAndProjectFactorySettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("automation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Playbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<string>("Harness")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("harness");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("MaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OnFailureStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("on_failure_state_id");

                    b.Property<Guid?>("OnSuccessStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("on_success_state_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id")
                        .HasName("pk_playbooks");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_playbooks_project_id");

                    b.HasIndex("ProjectId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_playbooks_default_project")
                        .HasFilter("is_default");

                    b.ToTable("playbooks", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_playbooks_harness", "harness IN ('claude', 'codex', 'opencode')");

                            t.HasCheckConstraint("ck_playbooks_max_minutes", "max_minutes BETWEEN 5 AND 720");

                            t.HasCheckConstraint("ck_playbooks_name", "length(btrim(name)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.ProjectFactorySettings", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("DefaultAgentId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("default_agent_id");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("main")
                        .HasColumnName("default_branch");

                    b.Property<string>("LocalPathHint")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("local_path_hint");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RepoFullName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repo_full_name");

                    b.Property<short>("RepoSource")
                        .HasColumnType("smallint")
                        .HasColumnName("repo_source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProjectId")
                        .HasName("pk_project_settings");

                    b.ToTable("project_settings", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_project_settings_default_branch", "length(btrim(default_branch)) BETWEEN 1 AND 255");

                            t.HasCheckConstraint("ck_project_settings_github_repo", "repo_source <> 0 OR repo_full_name IS NOT NULL");

                            t.HasCheckConstraint("ck_project_settings_repo_source", "repo_source IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capabilities")
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("registered_by");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("token_prefix");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_runners");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_runners_organization_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_runners_token_hash");

                    b.ToTable("runners", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_runners_deleted_is_disabled", "deleted_at IS NULL OR disabled_at IS NOT NULL");

                            t.HasCheckConstraint("ck_runners_name", "length(btrim(name)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_runners_token_hash", "token_hash ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_runners_token_prefix", "length(token_prefix) = 8");
                        });
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_outbox_messages_dead_lettered")
                        .HasFilter("dead_lettered_at IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OrganizationId", "At")
                        .HasDatabaseName("ix_audit_log_organization_id_at");

                    b.HasIndex("UserId", "At")
                        .HasDatabaseName("ix_audit_log_user_id_at");

                    b.HasIndex("EntityType", "EntityId", "At")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_at");

                    b.ToTable("audit_log", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
