// <auto-generated />
using System;
using Aictiq.Modules.Automation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aictiq.Modules.Automation.Migrations
{
    [DbContext(typeof(AutomationDbContext))]
    partial class AutomationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("automation")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Playbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<string>("Harness")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("harness");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<int>("MaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OnFailureStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("on_failure_state_id");

                    b.Property<Guid?>("OnSuccessStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("on_success_state_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid?>("WikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id")
                        .HasName("pk_playbooks");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_playbooks_project_id");

                    b.HasIndex("ProjectId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_playbooks_default_project")
                        .HasFilter("is_default");

                    b.ToTable("playbooks", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_playbooks_harness", "harness IN ('claude', 'codex', 'opencode')");

                            t.HasCheckConstraint("ck_playbooks_max_minutes", "max_minutes BETWEEN 5 AND 720");

                            t.HasCheckConstraint("ck_playbooks_name", "length(btrim(name)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.ProjectFactorySettings", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("DefaultAgentId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("default_agent_id");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasDefaultValue("main")
                        .HasColumnName("default_branch");

                    b.Property<string>("LocalPathHint")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("local_path_hint");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RepoFullName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repo_full_name");

                    b.Property<short>("RepoSource")
                        .HasColumnType("smallint")
                        .HasColumnName("repo_source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ProjectId")
                        .HasName("pk_project_settings");

                    b.ToTable("project_settings", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_project_settings_default_branch", "length(btrim(default_branch)) BETWEEN 1 AND 255");

                            t.HasCheckConstraint("ck_project_settings_github_repo", "repo_source <> 0 OR repo_full_name IS NOT NULL");

                            t.HasCheckConstraint("ck_project_settings_repo_source", "repo_source IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Rule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("created_by");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("RequiredLabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_label_id");

                    b.Property<Guid>("TriggerStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_state_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_rules");

                    b.HasIndex("PlaybookId")
                        .HasDatabaseName("ix_rules_playbook_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_rules_project_id");

                    b.ToTable("rules", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_rules_agent_user_id", "length(btrim(agent_user_id)) BETWEEN 1 AND 64");

                            t.HasCheckConstraint("ck_rules_name", "length(btrim(name)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.RuleFiring", b =>
                {
                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("skip_reason");

                    b.HasKey("RuleId", "ItemId", "EventId")
                        .HasName("pk_rule_firings");

                    b.HasIndex("RuleId", "At")
                        .HasDatabaseName("ix_rule_firings_rule_at");

                    b.ToTable("rule_firings", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_rule_firings_run_or_skip", "run_id IS NULL OR skip_reason IS NULL");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_token_id");

                    b.Property<string>("AgentUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agent_user_id");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("branch_name");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancel_requested_at");

                    b.Property<decimal?>("CostUsd")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("cost_usd");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("exit_code");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Harness")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("harness");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("input_tokens");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("item_key");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<int>("MaxMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("max_minutes");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OutcomeSummary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("outcome_summary");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint")
                        .HasColumnName("output_tokens");

                    b.Property<Guid>("PlaybookId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_id");

                    b.Property<Guid?>("PlaybookRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("playbook_revision_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt_snapshot");

                    b.Property<string>("PullRequestUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("pull_request_url");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requested_by");

                    b.Property<Guid?>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<Guid?>("RunnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("runner_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.HasIndex("RuleId")
                        .HasDatabaseName("ix_runs_rule_id");

                    b.HasIndex("ProjectId", "QueuedAt")
                        .HasDatabaseName("ix_runs_project_queued");

                    b.HasIndex("OrganizationId", "Status", "QueuedAt")
                        .HasDatabaseName("ix_runs_organization_status_queued");

                    b.HasIndex(new[] { "ItemId" }, "ix_runs_item")
                        .HasDatabaseName("ix_runs_item");

                    b.HasIndex(new[] { "ItemId" }, "ux_runs_item_live")
                        .IsUnique()
                        .HasDatabaseName("ux_runs_item_live")
                        .HasFilter("status < 3");

                    b.ToTable("runs", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_runs_finished_status", "(finished_at IS NOT NULL) = (status >= 3)");

                            t.HasCheckConstraint("ck_runs_max_minutes", "max_minutes BETWEEN 5 AND 720");

                            t.HasCheckConstraint("ck_runs_requested_by_xor_rule", "(requested_by IS NOT NULL) <> (rule_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_runs_status", "status BETWEEN 0 AND 6");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.RunLogChunk", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Stream")
                        .HasColumnType("smallint")
                        .HasColumnName("stream");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("text");

                    b.HasKey("RunId", "Seq")
                        .HasName("pk_run_log_chunks");

                    b.ToTable("run_log_chunks", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_run_log_chunks_seq", "seq >= 0");

                            t.HasCheckConstraint("ck_run_log_chunks_stream", "stream BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Runner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capabilities")
                        .HasColumnType("jsonb")
                        .HasColumnName("capabilities");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("registered_by");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("token_prefix");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_runners");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_runners_organization_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_runners_token_hash");

                    b.ToTable("runners", "automation", t =>
                        {
                            t.HasCheckConstraint("ck_runners_deleted_is_disabled", "deleted_at IS NULL OR disabled_at IS NOT NULL");

                            t.HasCheckConstraint("ck_runners_name", "length(btrim(name)) BETWEEN 1 AND 100");

                            t.HasCheckConstraint("ck_runners_token_hash", "token_hash ~ '^[0-9A-F]{64}$'");

                            t.HasCheckConstraint("ck_runners_token_prefix", "length(token_prefix) = 8");
                        });
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_outbox_messages_dead_lettered")
                        .HasFilter("dead_lettered_at IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OrganizationId", "At")
                        .HasDatabaseName("ix_audit_log_organization_id_at");

                    b.HasIndex("UserId", "At")
                        .HasDatabaseName("ix_audit_log_user_id_at");

                    b.HasIndex("EntityType", "EntityId", "At")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_at");

                    b.ToTable("audit_log", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.Rule", b =>
                {
                    b.HasOne("Aictiq.Modules.Automation.Domain.Playbook", null)
                        .WithMany()
                        .HasForeignKey("PlaybookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rules_playbooks_playbook_id");
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.RuleFiring", b =>
                {
                    b.HasOne("Aictiq.Modules.Automation.Domain.Rule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_firings_rules_rule_id");
                });

            modelBuilder.Entity("Aictiq.Modules.Automation.Domain.RunLogChunk", b =>
                {
                    b.HasOne("Aictiq.Modules.Automation.Domain.Run", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_log_chunks_runs_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
