<script setup lang="ts">
import { computed, ref } from 'vue'
import { useQuery } from '@tanstack/vue-query'
import { getAudit, auditExportUrl, type AuditEntry } from '@/api/audit'
import SettingsSection from '@/components/settings/SettingsSection.vue'
const props = defineProps<{ slug: string }>(); const actor = ref(''); const action = ref(''); const page = ref(0); const selected = ref<AuditEntry | null>(null)
const query = computed(() => ({ actor: actor.value || undefined, action: action.value || undefined, page: page.value }))
const audit = useQuery({ queryKey: computed(() => ['audit', props.slug, query.value]), queryFn: () => getAudit(props.slug, query.value) })
const auditData = computed(() => audit.data.value)
</script>
<template><SettingsSection title="Audit log" description="Organization changes and their actors."><div class="mb-4 flex flex-wrap gap-2"><input v-model="actor" class="border-input rounded border px-2 py-1 text-sm" placeholder="Actor id" /><input v-model="action" class="border-input rounded border px-2 py-1 text-sm" placeholder="Action" /><a class="rounded border px-3 py-1 text-sm" :href="auditExportUrl(slug, query)">Export CSV</a></div><p v-if="audit.isError.value" class="text-destructive">Audit log could not be loaded.</p><table v-else class="w-full text-left text-sm"><thead><tr class="text-muted-foreground"><th>When</th><th>Actor</th><th>Action</th><th>Entity</th></tr></thead><tbody><tr v-for="entry in auditData?.items" :key="entry.id" class="border-t hover:bg-muted/50" tabindex="0" @click="selected = entry" @keydown.enter="selected = entry"><td class="py-2">{{ new Date(entry.at).toLocaleString() }}</td><td>{{ entry.userId ?? 'System' }}</td><td>{{ entry.field }}</td><td>{{ entry.entityType }} · {{ entry.entityId }}</td></tr></tbody></table><div class="mt-4 flex gap-2"><button :disabled="!page" class="rounded border px-2 py-1" @click="page--">Previous</button><button :disabled="!auditData?.hasMore" class="rounded border px-2 py-1" @click="page++">Next</button></div><div v-if="selected" class="fixed inset-0 z-50 bg-black/30 p-4" @click.self="selected = null"><section class="bg-background ml-auto h-full max-w-lg overflow-auto p-5"><button class="float-right" @click="selected = null">Close</button><h2 class="font-semibold">Audit detail</h2><pre class="mt-4 text-xs">{{ JSON.stringify(selected, null, 2) }}</pre></section></div></SettingsSection></template>
