// <auto-generated />
using System;
using Aictiq.Modules.Billing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aictiq.Modules.Billing.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260910141432_StripeSubscriptions")]
    partial class StripeSubscriptions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.BillingPlan", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("HumanSeatPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("human_seat_price");

                    b.Property<int?>("IncludedAgentsPerHuman")
                        .HasColumnType("integer")
                        .HasColumnName("included_agents_per_human");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.HasKey("Code")
                        .HasName("pk_plans");

                    b.ToTable("plans", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_plans_included_agents", "included_agents_per_human IS NULL OR included_agents_per_human >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Code = "self_hosted",
                            HumanSeatPrice = 0m,
                            Limits = "{\"SeatsHuman\":null,\"SeatsAgent\":null,\"Projects\":null,\"StorageBytes\":null,\"Features\":[\"webhooks\",\"page_permissions\",\"audit_export\"]}"
                        },
                        new
                        {
                            Code = "free",
                            HumanSeatPrice = 0m,
                            Limits = "{\"SeatsHuman\":5,\"SeatsAgent\":1,\"Projects\":3,\"StorageBytes\":1073741824,\"Features\":null}"
                        },
                        new
                        {
                            Code = "starter",
                            HumanSeatPrice = 9m,
                            IncludedAgentsPerHuman = 3,
                            Limits = "{\"SeatsHuman\":20,\"SeatsAgent\":5,\"Projects\":20,\"StorageBytes\":10737418240,\"Features\":null}"
                        },
                        new
                        {
                            Code = "team",
                            HumanSeatPrice = 15m,
                            Limits = "{\"SeatsHuman\":null,\"SeatsAgent\":25,\"Projects\":null,\"StorageBytes\":107374182400,\"Features\":[\"webhooks\",\"page_permissions\",\"audit_export\"]}"
                        },
                        new
                        {
                            Code = "enterprise",
                            HumanSeatPrice = 19m,
                            Limits = "{\"SeatsHuman\":null,\"SeatsAgent\":null,\"Projects\":null,\"StorageBytes\":null,\"Features\":[\"webhooks\",\"page_permissions\",\"audit_export\",\"sso\",\"scim\"]}"
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.StripeEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stripe_events");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_stripe_events_received_at");

                    b.ToTable("stripe_events", "billing");
                });

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<DateTimeOffset?>("GraceEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_ends_at");

                    b.Property<DateTimeOffset?>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("PaymentFailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_failed_at");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<int>("SeatsAgent")
                        .HasColumnType("integer")
                        .HasColumnName("seats_agent");

                    b.Property<int>("SeatsHuman")
                        .HasColumnType("integer")
                        .HasColumnName("seats_human");

                    b.Property<DateTimeOffset?>("SeatsSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seats_synced_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("GraceEndsAt")
                        .HasDatabaseName("ix_subscriptions_grace_ends_at")
                        .HasFilter("grace_ends_at IS NOT NULL");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_organization_id");

                    b.HasIndex("Plan")
                        .HasDatabaseName("ix_subscriptions_plan");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_stripe_customer_id")
                        .HasFilter("stripe_customer_id IS NOT NULL");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_stripe_subscription_id")
                        .HasFilter("stripe_subscription_id IS NOT NULL");

                    b.ToTable("subscriptions", "billing", t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_billing_has_subscription", "status NOT IN (3, 4, 5, 7) OR stripe_subscription_id IS NOT NULL");

                            t.HasCheckConstraint("ck_subscriptions_grace", "(payment_failed_at IS NULL) = (grace_ends_at IS NULL) AND (grace_ends_at IS NULL OR grace_ends_at > payment_failed_at)");

                            t.HasCheckConstraint("ck_subscriptions_seats", "seats_human >= 0 AND seats_agent >= 0");

                            t.HasCheckConstraint("ck_subscriptions_status", "status BETWEEN 0 AND 8");

                            t.HasCheckConstraint("ck_subscriptions_subscription_has_customer", "stripe_subscription_id IS NULL OR stripe_customer_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.UsageSnapshot", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Agents")
                        .HasColumnType("integer")
                        .HasColumnName("agents");

                    b.Property<int>("Humans")
                        .HasColumnType("integer")
                        .HasColumnName("humans");

                    b.Property<int>("Projects")
                        .HasColumnType("integer")
                        .HasColumnName("projects");

                    b.Property<long>("StorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_bytes");

                    b.HasKey("OrganizationId", "Day")
                        .HasName("pk_usage_snapshots");

                    b.HasIndex("OrganizationId", "Day")
                        .HasDatabaseName("ix_usage_snapshots_organization_id_day");

                    b.ToTable("usage_snapshots", "billing");
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_outbox_messages_dead_lettered")
                        .HasFilter("dead_lettered_at IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OrganizationId", "At")
                        .HasDatabaseName("ix_audit_log_organization_id_at");

                    b.HasIndex("UserId", "At")
                        .HasDatabaseName("ix_audit_log_user_id_at");

                    b.HasIndex("EntityType", "EntityId", "At")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_at");

                    b.ToTable("audit_log", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.Subscription", b =>
                {
                    b.HasOne("Aictiq.Modules.Billing.Domain.BillingPlan", null)
                        .WithMany()
                        .HasForeignKey("Plan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan");
                });
#pragma warning restore 612, 618
        }
    }
}
