// <auto-generated />
using System;
using Aictiq.Modules.Billing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aictiq.Modules.Billing.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260910130527_InitialBilling")]
    partial class InitialBilling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.BillingPlan", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("HumanSeatPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("human_seat_price");

                    b.Property<string>("Limits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("limits");

                    b.HasKey("Code")
                        .HasName("pk_plans");

                    b.ToTable("plans", "billing");

                    b.HasData(
                        new
                        {
                            Code = "self_hosted",
                            HumanSeatPrice = 0m,
                            Limits = "{\"SeatsHuman\":null,\"SeatsAgent\":null,\"Projects\":null,\"StorageBytes\":null,\"Features\":[\"webhooks\",\"page_permissions\",\"audit_export\"]}"
                        },
                        new
                        {
                            Code = "free",
                            HumanSeatPrice = 0m,
                            Limits = "{\"SeatsHuman\":5,\"SeatsAgent\":1,\"Projects\":3,\"StorageBytes\":1073741824,\"Features\":null}"
                        },
                        new
                        {
                            Code = "starter",
                            HumanSeatPrice = 9m,
                            Limits = "{\"SeatsHuman\":20,\"SeatsAgent\":5,\"Projects\":20,\"StorageBytes\":10737418240,\"Features\":null}"
                        },
                        new
                        {
                            Code = "team",
                            HumanSeatPrice = 15m,
                            Limits = "{\"SeatsHuman\":null,\"SeatsAgent\":25,\"Projects\":null,\"StorageBytes\":107374182400,\"Features\":[\"webhooks\",\"page_permissions\",\"audit_export\"]}"
                        },
                        new
                        {
                            Code = "enterprise",
                            HumanSeatPrice = 19m,
                            Limits = "{\"SeatsHuman\":null,\"SeatsAgent\":null,\"Projects\":null,\"StorageBytes\":null,\"Features\":[\"webhooks\",\"page_permissions\",\"audit_export\",\"sso\",\"scim\"]}"
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.Billing.Domain.UsageSnapshot", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<int>("Agents")
                        .HasColumnType("integer")
                        .HasColumnName("agents");

                    b.Property<int>("Humans")
                        .HasColumnType("integer")
                        .HasColumnName("humans");

                    b.Property<int>("Projects")
                        .HasColumnType("integer")
                        .HasColumnName("projects");

                    b.Property<long>("StorageBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_bytes");

                    b.HasKey("OrganizationId", "Day")
                        .HasName("pk_usage_snapshots");

                    b.HasIndex("OrganizationId", "Day")
                        .HasDatabaseName("ix_usage_snapshots_organization_id_day");

                    b.ToTable("usage_snapshots", "billing");
                });
#pragma warning restore 612, 618
        }
    }
}
