import js from '@eslint/js'
import type { Linter } from 'eslint'
import prettierSkipFormatting from '@vue/eslint-config-prettier/skip-formatting'
import { defineConfigWithVueTs, vueTsConfigs } from '@vue/eslint-config-typescript'
import pluginVue from 'eslint-plugin-vue'
import globals from 'globals'

// The explicit annotation keeps the emitted type from naming a transitively-installed
// package path (pnpm's strict node_modules makes that unportable).
const config: Linter.Config[] = defineConfigWithVueTs(
  {
    name: 'aictiq/ignores',
    // shadcn-vue components are vendored, not authored here — they are re-generated by
    // the CLI, so lint noise in them is not actionable.
    ignores: ['dist/**', 'coverage/**', 'src/components/ui/**'],
  },
  js.configs.recommended,
  pluginVue.configs['flat/recommended'],
  vueTsConfigs.recommended,
  {
    name: 'aictiq/app',
    files: ['**/*.{ts,mts,vue}'],
    languageOptions: {
      globals: { ...globals.browser },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      // Views and route components are single-word by convention in this app.
      'vue/multi-word-component-names': 'off',
    },
  },
  {
    name: 'aictiq/node-configs',
    files: ['*.config.ts', 'vite.config.ts', 'vitest.config.ts', 'eslint.config.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },
  prettierSkipFormatting,
) as Linter.Config[]

export default config
