// <auto-generated />
using System;
using Aictiq.Modules.WorkItems;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Aictiq.Modules.WorkItems.Migrations
{
    [DbContext(typeof(WorkItemsDbContext))]
    [Migration("20260917123611_RunOutcomeComments")]
    partial class RunOutcomeComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("work")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("object_key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("uploaded_by");

                    b.Property<Guid?>("WikiPageId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiki_page_id");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_attachments_comment_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_attachments_item_id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_attachments_object_key");

                    b.HasIndex("ProjectId", "CommentId")
                        .HasDatabaseName("ix_attachments_project_id_comment_id");

                    b.HasIndex("ProjectId", "ItemId")
                        .HasDatabaseName("ix_attachments_project_id_item_id");

                    b.HasIndex("ProjectId", "WikiPageId")
                        .HasDatabaseName("ix_attachments_project_id_wiki_page_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_attachments_status_created_at");

                    b.ToTable("attachments", "work", t =>
                        {
                            t.HasCheckConstraint("ck_attachments_owner_and_status", "(status = 0 AND item_id IS NULL AND comment_id IS NULL AND wiki_page_id IS NULL) OR (status = 1 AND ((item_id IS NOT NULL)::integer + (comment_id IS NOT NULL)::integer + (wiki_page_id IS NOT NULL)::integer = 1))");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_boards");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_boards_team_id");

                    b.HasIndex("OrganizationId", "TeamId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ux_boards_team_kind");

                    b.ToTable("boards", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("author_id");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.PrimitiveCollection<string[]>("MentionedUserIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("mentioned_user_ids");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<NpgsqlTsVector>("Search")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(body_markdown, '')) ||\nto_tsvector('simple', coalesce(body_markdown, ''))", true);

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("ItemId", "CreatedAt")
                        .HasDatabaseName("ix_comments_item_id_created_at");

                    b.HasIndex("ItemId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_comments_item_id_event_id")
                        .HasFilter("event_id IS NOT NULL");

                    b.ToTable("comments", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.CommentReaction", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<string>("Emoji")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("emoji");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("CommentId", "UserId", "Emoji")
                        .HasName("pk_comment_reactions");

                    b.ToTable("comment_reactions", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.CommentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_markdown");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("edited_by");

                    b.HasKey("Id")
                        .HasName("pk_comment_revisions");

                    b.HasIndex("CommentId", "EditedAt")
                        .HasDatabaseName("ix_comment_revisions_comment_id_edited_at");

                    b.ToTable("comment_revisions", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.CsvImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedRows")
                        .HasColumnType("integer")
                        .HasColumnName("created_rows");

                    b.Property<string>("Csv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("csv");

                    b.PrimitiveCollection<string[]>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("errors");

                    b.Property<string>("MappingJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mapping_json");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("project_key");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("requested_by");

                    b.Property<int>("SkippedRows")
                        .HasColumnType("integer")
                        .HasColumnName("skipped_rows");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id")
                        .HasName("pk_csv_import_jobs");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_csv_import_jobs_project_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_csv_import_jobs_status_created_at");

                    b.ToTable("csv_import_jobs", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id")
                        .HasName("pk_item_history");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_item_history_event_id");

                    b.HasIndex("ItemId", "At")
                        .HasDatabaseName("ix_item_history_item_id_at");

                    b.ToTable("item_history", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemLabel", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("added_by");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("ItemId", "LabelId")
                        .HasName("pk_item_labels");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_item_labels_label_id");

                    b.ToTable("item_labels", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("State")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_item_links");

                    b.HasIndex("ItemId", "Provider", "Kind", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_item_links_idempotency");

                    b.ToTable("item_links", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemRelation", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("SourceId", "TargetId", "Kind")
                        .HasName("pk_item_relations");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_item_relations_target_id");

                    b.ToTable("item_relations", "work", t =>
                        {
                            t.HasCheckConstraint("ck_item_relations_not_self", "source_id <> target_id");

                            t.HasCheckConstraint("ck_item_relations_related_order", "kind <> 0 OR source_id < target_id");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("DefaultLabelIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("default_label_ids");

                    b.Property<short?>("DefaultPriority")
                        .HasColumnType("smallint")
                        .HasColumnName("default_priority");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_markdown");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_item_templates");

                    b.HasIndex("OrganizationId", "ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_item_templates_name");

                    b.HasIndex("ProjectId", "Type", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_item_templates_default_type")
                        .HasFilter("is_default");

                    b.ToTable("item_templates", "work", t =>
                        {
                            t.HasCheckConstraint("ck_item_templates_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemWatcher", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("MutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("muted_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<short>("Reason")
                        .HasColumnType("smallint")
                        .HasColumnName("reason");

                    b.HasKey("ItemId", "UserId")
                        .HasName("pk_watchers");

                    b.HasIndex("ItemId", "MutedAt")
                        .HasDatabaseName("ix_watchers_item_id_muted_at");

                    b.ToTable("watchers", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("description");

                    b.Property<string>("Group")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("group_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_labels_project_id");

                    b.ToTable("labels", "work", t =>
                        {
                            t.HasCheckConstraint("ck_labels_color_format", "color IS NULL OR color ~ '^#[0-9A-Fa-f]{6}$'");

                            t.HasCheckConstraint("ck_labels_group_not_blank", "group_name IS NULL OR length(btrim(group_name)) > 0");

                            t.HasCheckConstraint("ck_labels_name_not_blank", "length(btrim(name)) > 0 AND length(name) <= 50");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ProjectSequence", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("NextNumber")
                        .HasColumnType("integer")
                        .HasColumnName("next_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("ProjectId")
                        .HasName("pk_project_sequences");

                    b.ToTable("project_sequences", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("Columns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("columns");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("filter");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Sort")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sort");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_saved_views");

                    b.HasIndex("ProjectId", "IsShared", "Name")
                        .HasDatabaseName("ix_saved_views_project_id_is_shared_name");

                    b.HasIndex("ProjectId", "OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_saved_views_owner_name");

                    b.ToTable("saved_views", "work", t =>
                        {
                            t.HasCheckConstraint("ck_saved_views_name_not_blank", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoCreateNext")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_create_next");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("state");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sprints");

                    b.HasIndex("TeamId", "StartsOn")
                        .HasDatabaseName("ix_sprints_team_starts_on");

                    b.HasIndex("TeamId", "State")
                        .HasDatabaseName("ix_sprints_team_state");

                    b.ToTable("sprints", "work", t =>
                        {
                            t.HasCheckConstraint("ck_sprints_dates", "ends_on > starts_on");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.SprintCapacity", b =>
                {
                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.Property<int>("DaysOff")
                        .HasColumnType("integer")
                        .HasColumnName("days_off");

                    b.Property<decimal>("HoursPerDay")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("hours_per_day");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("SprintId", "UserId")
                        .HasName("pk_sprint_capacity");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_sprint_capacity_organization_id_user_id");

                    b.ToTable("sprint_capacity", "work", t =>
                        {
                            t.HasCheckConstraint("ck_sprint_capacity_days_off", "days_off >= 0");

                            t.HasCheckConstraint("ck_sprint_capacity_hours_per_day", "hours_per_day BETWEEN 0 AND 24");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.SprintScopeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<short>("Change")
                        .HasColumnType("smallint")
                        .HasColumnName("change");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal?>("Points")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("points");

                    b.Property<decimal?>("RemainingHours")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("remaining_hours");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.HasKey("Id")
                        .HasName("pk_sprint_scope_log");

                    b.HasIndex("ItemId", "At")
                        .HasDatabaseName("ix_sprint_scope_log_item_id_at");

                    b.HasIndex("SprintId", "At")
                        .HasDatabaseName("ix_sprint_scope_log_sprint_id_at");

                    b.ToTable("sprint_scope_log", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.WorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssigneeId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assignee_id");

                    b.Property<Guid?>("BoardColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_column_id");

                    b.Property<DateTimeOffset?>("ClaimHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_heartbeat_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("CompletedHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("completed_hours");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("created_by");

                    b.Property<string>("DescriptionHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_html");

                    b.Property<string>("DescriptionMarkdown")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_markdown");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("EstimateHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("estimate_hours");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_ref");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<decimal?>("Points")
                        .HasColumnType("numeric")
                        .HasColumnName("points");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("project_key");

                    b.Property<string>("Rank")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("rank");

                    b.Property<decimal?>("RemainingHours")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("remaining_hours");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Resolution")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<NpgsqlTsVector>("Search")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title, '')), 'A') ||\nsetweight(to_tsvector('simple', coalesce(title, '')), 'A') ||\nsetweight(to_tsvector('english', coalesce(project_key || '-' || number::text, '')), 'A') ||\nsetweight(to_tsvector('simple', coalesce(project_key || '-' || number::text, '')), 'A') ||\nsetweight(to_tsvector('english', coalesce(label_search, '')), 'B') ||\nsetweight(to_tsvector('simple', coalesce(label_search, '')), 'B') ||\nsetweight(to_tsvector('english', coalesce(description_markdown, '')), 'C') ||\nsetweight(to_tsvector('simple', coalesce(description_markdown, '')), 'C')", true);

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_items_assignee_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_items_parent_id");

                    b.HasIndex("StateId")
                        .HasDatabaseName("ix_items_state_id");

                    b.HasIndex("ProjectId", "ExternalRef")
                        .IsUnique()
                        .HasDatabaseName("ux_items_project_external_ref")
                        .HasFilter("external_ref IS NOT NULL");

                    b.HasIndex("ProjectId", "Rank")
                        .HasDatabaseName("ix_items_project_rank");

                    b.HasIndex("ProjectId", "StateId")
                        .HasDatabaseName("ix_items_project_id_state_id");

                    b.HasIndex("TeamId", "SprintId")
                        .HasDatabaseName("ix_items_team_id_sprint_id");

                    b.HasIndex("OrganizationId", "ProjectId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_items_organization_id_project_id_number");

                    b.HasIndex("OrganizationId", "ProjectKey", "Number")
                        .HasDatabaseName("ix_items_organization_id_project_key_number");

                    b.HasIndex("TeamId", "BoardColumnId", "Rank")
                        .HasDatabaseName("ix_items_team_board_column_rank");

                    b.ToTable("items", "work", t =>
                        {
                            t.HasCheckConstraint("ck_items_hours_nonnegative", "(estimate_hours IS NULL OR estimate_hours >= 0) AND (remaining_hours IS NULL OR remaining_hours >= 0) AND (completed_hours IS NULL OR completed_hours >= 0)");

                            t.HasCheckConstraint("ck_items_hours_task_or_bug", "type IN (3, 4) OR (estimate_hours IS NULL AND remaining_hours IS NULL AND completed_hours IS NULL)");

                            t.HasCheckConstraint("ck_items_parent_not_self", "parent_id IS NULL OR parent_id <> id");

                            t.HasCheckConstraint("ck_items_title_not_blank", "length(btrim(title)) > 0");
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_workflows");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_workflows_project_id");

                    b.HasIndex("ProjectId", "IsDefault")
                        .IsUnique()
                        .HasDatabaseName("ux_workflows_default_project")
                        .HasFilter("is_default");

                    b.HasIndex("OrganizationId", "ProjectId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_workflows_organization_id_project_id_name");

                    b.ToTable("workflows", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.WorkflowState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Category")
                        .HasColumnType("smallint")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<bool>("IsInitial")
                        .HasColumnType("boolean")
                        .HasColumnName("is_initial");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_states");

                    b.HasIndex("WorkflowId", "IsInitial")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_states_initial")
                        .HasFilter("is_initial");

                    b.HasIndex("WorkflowId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_workflow_states_name");

                    b.ToTable("workflow_states", "work");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.WorkflowTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FromStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_state_id");

                    b.Property<Guid>("ToStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_state_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("pk_workflow_transitions");

                    b.HasIndex("FromStateId")
                        .HasDatabaseName("ix_workflow_transitions_from_state_id");

                    b.HasIndex("ToStateId")
                        .HasDatabaseName("ix_workflow_transitions_to_state_id");

                    b.HasIndex("WorkflowId", "FromStateId", "ToStateId")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_transitions_workflow_id_from_state_id_to_state_id");

                    b.ToTable("workflow_transitions", "work");
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("DeadLetteredAt")
                        .HasDatabaseName("ix_outbox_messages_dead_lettered")
                        .HasFilter("dead_lettered_at IS NOT NULL");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL AND dead_lettered_at IS NULL");

                    b.ToTable("outbox_messages", "shared", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.SharedKernel.Persistence.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("field");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("OrganizationId", "At")
                        .HasDatabaseName("ix_audit_log_organization_id_at");

                    b.HasIndex("UserId", "At")
                        .HasDatabaseName("ix_audit_log_user_id_at");

                    b.HasIndex("EntityType", "EntityId", "At")
                        .HasDatabaseName("ix_audit_log_entity_type_entity_id_at");

                    b.ToTable("audit_log", "audit", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Attachment", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_comments_comment_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_attachments_items_item_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Comment", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_items_item_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.CommentReaction", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_reactions_comments_comment_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.CommentRevision", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Comment", null)
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_revisions_comments_comment_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemHistory", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_history_items_item_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemLabel", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_labels_items_item_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_labels_labels_label_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemLink", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_links_items_item_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemRelation", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_relations_items_source_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_relations_items_target_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.ItemWatcher", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_watchers_items_item_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.SprintCapacity", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_capacity_sprints_sprint_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.SprintScopeLog", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_scope_log_items_item_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Sprint", null)
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_scope_log_sprints_sprint_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.WorkItem", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_items_items_parent_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkflowState", null)
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_workflow_states_state_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.WorkflowState", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Workflow", null)
                        .WithMany("States")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_states_workflows_workflow_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.WorkflowTransition", b =>
                {
                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkflowState", null)
                        .WithMany()
                        .HasForeignKey("FromStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_workflow_transitions_workflow_states_from_state_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.WorkflowState", null)
                        .WithMany()
                        .HasForeignKey("ToStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflow_states_to_state_id");

                    b.HasOne("Aictiq.Modules.WorkItems.Domain.Workflow", null)
                        .WithMany("Transitions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workflow_transitions_workflows_workflow_id");
                });

            modelBuilder.Entity("Aictiq.Modules.WorkItems.Domain.Workflow", b =>
                {
                    b.Navigation("States");

                    b.Navigation("Transitions");
                });
#pragma warning restore 612, 618
        }
    }
}
